In [13]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, SnowballStemmer

In [2]:
data = pd.read_excel('Online Retail.xlsx')
data

InvoiceNo StockCode                          Description  Quantity   
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6  \
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                    ...        ...         ...             ...  
541904 2011-12-09 12:50:00       0.85     12680.0          France  
541905 2011-12-09 12:50:00       2.10     12680.0          France  
541906 2011-12-09 12:50:00       4.15     12680.0          France  
541907 2011-12-09 12:50:00       4.15     12680.0          France  
541908 2011-12-09 12:50:00       4.95     12680.0          France  

[541909 rows x 8 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    541909 non-null  object        
 1   StockCode    541909 non-null  object        
 2   Description  540455 non-null  object        
 3   Quantity     541909 non-null  int64         
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      541909 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB


In [4]:
data = data[data["CustomerID"].notna()]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype         
---  ------       --------------   -----         
 0   InvoiceNo    406829 non-null  object        
 1   StockCode    406829 non-null  object        
 2   Description  406829 non-null  object        
 3   Quantity     406829 non-null  int64         
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64       
 6   CustomerID   406829 non-null  float64       
 7   Country      406829 non-null  object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB


In [28]:
data['InvoiceDay'] = data['InvoiceDate'].apply(lambda x: dt.datetime(x.year, x.month, x.day))

C:\Users\MR-14\AppData\Local\Temp\ipykernel_928\1841269460.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['InvoiceDay'] = data['InvoiceDate'].apply(lambda x: dt.datetime(x.year, x.month, x.day))


In [6]:
data.describe()

Quantity                    InvoiceDate      UnitPrice   
count  406829.000000                         406829  406829.000000  \
mean       12.061303  2011-07-10 16:30:57.879207424       3.460471   
min    -80995.000000            2010-12-01 08:26:00       0.000000   
25%         2.000000            2011-04-06 15:02:00       1.250000   
50%         5.000000            2011-07-31 11:48:00       1.950000   
75%        12.000000            2011-10-20 13:06:00       3.750000   
max     80995.000000            2011-12-09 12:50:00   38970.000000   
std       248.693370                            NaN      69.315162   

          CustomerID  
count  406829.000000  
mean    15287.690570  
min     12346.000000  
25%     13953.000000  
50%     15152.000000  
75%     16791.000000  
max     18287.000000  
std      1713.600303

In [10]:
porter_stemmer = PorterStemmer()
dataset = pd.DataFrame(columns=('title_body', 'category'))

for index, row in data.iterrows():
    title_body = row['Title'] + ' ' + row['Body']
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords.words('english')]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '')
    }

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [19]:
data

InvoiceNo StockCode                          Description  Quantity   
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6  \
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                    ...        ...         ...             ...  
541904 2011-12-09 12:50:00       0.85     12680.0          France  
541905 2011-12-09 12:50:00       2.10     12680.0          France  
541906 2011-12-09 12:50:00       4.15     12680.0          France  
541907 2011-12-09 12:50:00       4.15     12680.0          France  
541908 2011-12-09 12:50:00       4.95     12680.0          France  

[406829 rows x 8 columns]

In [8]:
word_tokenize(data["Description"][0])

['WHITE', 'HANGING', 'HEART', 'T-LIGHT', 'HOLDER']

In [9]:
[w for w in word_tokenize(data["Description"][0]) if not w in stopwords.words('english')]

['WHITE', 'HANGING', 'HEART', 'T-LIGHT', 'HOLDER']

In [20]:
porter_stemmer = PorterStemmer()

# Example words for stemming
words = [w for w in word_tokenize(data["Description"][0]) if not w in stopwords.words('english')]


# Apply stemming to each word
stemmed_words = [porter_stemmer.stem(word) for word in words]

# Print the results
print("Original words:", words)
print("Stemmed words:", stemmed_words)


Original words: ['WHITE', 'HANGING', 'HEART', 'T-LIGHT', 'HOLDER']
Stemmed words: ['white', 'hang', 'heart', 't-light', 'holder']


In [14]:


# Choose a language for stemming, for example, English
stemmer = SnowballStemmer(language='english')

# Example words to stem
words_to_stem = [w for w in word_tokenize(data["Description"][0]) if not w in stopwords.words('english')]


# Apply Snowball Stemmer
stemmed_words = [stemmer.stem(word) for word in words_to_stem]

# Print the results
print("Original words:", words_to_stem)
print("Stemmed words:", stemmed_words)


Original words: ['WHITE', 'HANGING', 'HEART', 'T-LIGHT', 'HOLDER']
Stemmed words: ['white', 'hang', 'heart', 't-light', 'holder']


In [19]:
lemma = nltk.wordnet.WordNetLemmatizer()

stemmed_words = [lemma.lemmatize(word) for word in words_to_stem]
stemmed_words


['WHITE', 'HANGING', 'HEART', 'T-LIGHT', 'HOLDER']

In [17]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\MR-14\AppData\Roaming\nltk_data...


True

In [25]:
from sklearn.feature_extraction.text import CountVectorizer
corpus = data["Description"]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()
print(X.toarray())
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


array(['10 balloons', '10 blue', '10 cards', ..., 'zinc watering',
       'zinc willie', 'zinc wire'], dtype=object)

In [27]:
len(vectorizer2.get_feature_names_out())


6967

In [35]:
data["Cost"] = data["Quantity"] * data["UnitPrice"]

C:\Users\MR-14\AppData\Local\Temp\ipykernel_928\3696299223.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Cost"] = data["Quantity"] * data["UnitPrice"]


In [36]:
data

InvoiceNo StockCode                          Description  Quantity   
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6  \
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3   

               InvoiceDate  UnitPrice  CustomerID         Country InvoiceDay   
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom 2010-12-01  \
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom 2010-12-01   
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom 2010-12-01   
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom 2010-12-01   
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom 2010-12-01   
...                    ...        ...         ...             ...        ...   
541904 2011-12-09 12:50:00       0.85     12680.0          France 2011-12-09   
541905 2011-12-09 12:50:00       2.10     12680.0          France 2011-12-09   
541906 2011-12-09 12:50:00       4.15     12680.0          France 2011-12-09   
541907 2011-12-09 12:50:00       4.15     12680.0          France 2011-12-09   
541908 2011-12-09 12:50:00       4.95     12680.0          France 2011-12-09   

         Cost  
0       15.30  
1       20.34  
2       22.00  
3       20.34  
4       20.34  
...       ...  
541904  10.20  
541905  12.60  
541906  16.60  
541907  16.60  
541908  14.85  

[406829 rows x 10 columns]

In [141]:
b = data.groupby("CustomerID").agg(All_Cost = ("Cost", "sum"),
                                   All_Description = ("Description", lambda x: x),
                                   Country = ("Country", lambda x: list(set(x))[0]),
                                   InvoiceNo_count = ("InvoiceNo", "count")
                                  )
b

All_Cost                                    All_Description   
CustomerID                                                                
12346.0         0.00  [MEDIUM CERAMIC TOP STORAGE JAR, MEDIUM CERAMI...  \
12347.0      4310.00  [BLACK CANDELABRA T-LIGHT HOLDER, AIRLINE BAG ...   
12348.0      1797.24  [72 SWEETHEART FAIRY CAKE CASES, 60 CAKE CASES...   
12349.0      1757.55  [PARISIENNE CURIO CABINET, SWEETHEART WALL TID...   
12350.0       334.40  [CHOCOLATE THIS WAY METAL SIGN, METAL SIGN NEI...   
...              ...                                                ...   
18280.0       180.60  [WOOD BLACK BOARD ANT WHITE FINISH, RETROSPOT ...   
18281.0        80.82  [ROBOT BIRTHDAY CARD, CARD CIRCUS PARADE, PENN...   
18282.0       176.60  [ANTIQUE CREAM CUTLERY CUPBOARD, FRENCH STYLE ...   
18283.0      2094.88  [CHARLOTTE BAG PINK POLKADOT, LUNCH BAG WOODLA...   
18287.0      1837.28  [SMALL PURPLE BABUSHKA NOTEBOOK , SMALL RED BA...   

                   Country  InvoiceNo_count  
CustomerID                                   
12346.0     United Kingdom                2  
12347.0            Iceland              182  
12348.0            Finland               31  
12349.0              Italy               73  
12350.0             Norway               17  
...                    ...              ...  
18280.0     United Kingdom               10  
18281.0     United Kingdom                7  
18282.0     United Kingdom               13  
18283.0     United Kingdom              756  
18287.0     United Kingdom               70  

[4372 rows x 4 columns]

In [142]:
b["All_Description"] = b["All_Description"].apply(lambda x: " ".join(list(set([h for s in [i.split() for i in x] for h in s]))))

In [143]:
b

All_Cost                                    All_Description   
CustomerID                                                                
12346.0         0.00                     CERAMIC STORAGE TOP MEDIUM JAR  \
12347.0      4310.00  CANDLESTICK BATH STRAINER TINS TREE SANDWICH S...   
12348.0      1797.24  SUNDAE RETROSPOT PINK DESIGN PAISLEY CASES LIP...   
12349.0      1757.55  PLASTERS RAIN GINGHAM TINS POT SPOONS PAISLEY ...   
12350.0       334.40  PLASTERS RETROSPOT MOD PLATE WITCH PAISLEY IN ...   
...              ...                                                ...   
18280.0       180.60  RETROSPOT TINS BUNTING COAT GUMBALL CADDY PAPE...   
18281.0        80.82  COAT GUMBALL CARD GIFT BABY LUNCH ROBOT CIRCUS...   
18282.0       176.60  SPOTS JUG FLANNEL BUNTING SUGAR PINK PAISLEY C...   
18283.0      2094.88  PLASTERS PLAYHOUSE TREE PEARS SPOT COSY SNAP T...   
18287.0      1837.28  BATH GINGHAM GLITTER TREE POT TOADSTOOLS BABUS...   

                   Country  InvoiceNo_count  
CustomerID                                   
12346.0     United Kingdom                2  
12347.0            Iceland              182  
12348.0            Finland               31  
12349.0              Italy               73  
12350.0             Norway               17  
...                    ...              ...  
18280.0     United Kingdom               10  
18281.0     United Kingdom                7  
18282.0     United Kingdom               13  
18283.0     United Kingdom              756  
18287.0     United Kingdom               70  

[4372 rows x 4 columns]

In [127]:
list(set([h for s in [i.split() for i in b["All_Description"][12346]] for h in s]))

['CERAMIC', 'STORAGE', 'TOP', 'MEDIUM', 'JAR']

In [49]:
data[data["CustomerID"]==12346]["Description"]

61619    MEDIUM CERAMIC TOP STORAGE JAR
61624    MEDIUM CERAMIC TOP STORAGE JAR
Name: Description, dtype: object

In [43]:
data[data["CustomerID"]==12346][]

InvoiceNo StockCode                     Description  Quantity   
61619    541431     23166  MEDIUM CERAMIC TOP STORAGE JAR     74215  \
61624   C541433     23166  MEDIUM CERAMIC TOP STORAGE JAR    -74215   

              InvoiceDate  UnitPrice  CustomerID         Country InvoiceDay   
61619 2011-01-18 10:01:00       1.04     12346.0  United Kingdom 2011-01-18  \
61624 2011-01-18 10:17:00       1.04     12346.0  United Kingdom 2011-01-18   

          Cost  
61619  77183.6  
61624 -77183.6

In [ ]:
data.groupby('CustomerID').agg({
    'InvoiceDay': lambda x: (pin_date - x.max()).days,
    'InvoiceNo': 'count',
    'TotalSum': 'sum'
})
" ".join()

In [ ]:
data.groupby("CustomerID").agg("Cost").sum()