In [10]:
import numpy as np

narr = np.array([1, 2, 3])
narr.resize((3, 3), refcheck=False)
print(narr)

for i in range(len(narr)):
    for j in range(len(narr[i])):
        if i == j:
            print(narr[i][j])

np.diag(narr)
np.repeat([4, 3, 2], 5)

[[1 2 3]
 [0 0 0]
 [0 0 0]]
1
0
0


array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [27]:
mr = np.arange(15) ** 2
print(mr)
mr[-5:-10:-3]

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196]


array([100,  49])

In [37]:
narr = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

narr[1:2, :]

array([[4, 5, 6]])

In [38]:
t = np.array([[[1, 5], [1, 8], [4, 1]],
             [[1, 1], [4, 6], [6, 2]],
             [[8, 1], [8, 8], [6, 5]]])
t

array([[[1, 5],
        [1, 8],
        [4, 1]],

       [[1, 1],
        [4, 6],
        [6, 2]],

       [[8, 1],
        [8, 8],
        [6, 5]]])

In [56]:
t[1:3, 0:2]

array([[[1, 1],
        [4, 6]],

       [[8, 1],
        [8, 8]]])

In [62]:
warr = np.zeros(narr.shape)
warr[0, 1] = True
# warr[2, 0] = True
# warr = warr.astype(bool)
warr

array([[0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
n = [1,2,3]
m = n
m[1]=33
n

[1, 33, 3]